apiVersion: batch/v1
kind: Job
metadata:
  name: cb-data-backup-${JOB_ID}
  namespace: ${NAMESPACE}
spec:
  template:
    spec:
      containers:
      - name: cb-data-backup
        image: 953030164212.dkr.ecr.us-east-1.amazonaws.com/glt-cb-backup:stablearchive
        resources:
          limits:
            cpu: 1
            memory: 512Mi
          requests:
            cpu: 1
            memory: 512Mi
        env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              key: aws-s3-key-id
              name: s3-bucket-creds
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              key: aws-s3-secret-key
              name: s3-bucket-creds
        - name: NODE_IP
          value: ${NODE_IP}
        - name: BUCKETS
          value: ${BUCKETS}
        - name: ADMIN_USER
          value: ${ADMIN_USER}
        - name: ADMIN_PASSWORD
          value: ${ADMIN_PASSWORD}
        - name: ENV_NAME
          value: ${ENV_NAME}
        - name: TAG
          value: ${TAG}
      restartPolicy: Never
