apiVersion: batch/v1
kind: Job
metadata:
  name: master-data-provision-${kubeJobID}
  namespace: ${NAMESPACE}
spec:
  template:
    spec:
      containers:
      - name: master-data-provision
        image: 953030164212.dkr.ecr.us-east-1.amazonaws.com/glt-master-data-provision:latest
        env:
        - name: CBHOST
          value: cb-${CB_CLUSTER}.glt-int.svc.cluster.local
        - name: CBUSER
          value: Administrator
        - name: CBPASS
          value: "${CBPASS}"
        - name: SERVICE
          value: "${SERVICE_NAME}"
        - name: MODE
          value: "${MODE}"
        - name: ENV_FOLDER
          value: "glt-master-data-provision/glt-int"
        - name: PRODUCT_VERSION
          value: "1"
        - name: AWS_REGION
          value: "us-east-1"
        - name: OVERRIDE_BUCKET
          value: "${OVERRIDE_BUCKET}"
        - name: BUCKET_NAME
          value: "${BUCKET_NAME}"
        - name: AWS_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              key: aws-s3-key-id
              name: s3-bucket-creds
        - name: AWS_SECRET_KEY
          valueFrom:
            secretKeyRef:
              key: aws-s3-secret-key
              name: s3-bucket-creds
      restartPolicy: Never
