apiVersion: v1
kind: Service
metadata:
  namespace: ${NAMESPACE}
  name: ${SERVICE_NAME}
  labels:
    app: ${SERVICE_NAME}
    tier: backend
spec:
  ports:
  - port: ${PORT}
  selector:
    app: ${SERVICE_NAME}
    tier: backend
